# Generated by Django 6.0.2 on 2026-02-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phones', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='phones.phonemodel')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shops.shop')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.servicetype')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['phone_model', 'service_type', 'price'], name='pricing_pri_phone_m_a3811f_idx'), models.Index(fields=['shop', 'phone_model'], name='pricing_pri_shop_id_acfadb_idx')],
                'unique_together': {('shop', 'phone_model', 'service_type')},
            },
        ),
    ]
